services:
  bot:
    build: 
      context: app
    ports:
      - "8000:8000"
    networks:
      - private-bot-network

  nginx:
    build: 
      context: nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - bot
    networks:
      - private-bot-network

networks:
  private-bot-network:
    driver: bridge
